# Generated by Django 5.2.3 on 2025-07-01 20:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('preferencia_notificacao', models.CharField(blank=True, choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Email e SMS', 'Email e SMS')], max_length=20)),
                ('aceitou_termos', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('comprimento', models.FloatField()),
                ('largura', models.FloatField()),
                ('altura', models.FloatField()),
                ('capacidade_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Escavado', 'Escavado'), ('Tanque-rede', 'Tanque-rede'), ('Alvenaria', 'Alvenaria'), ('Fibra de vidro', 'Fibra de vidro'), ('Outro', 'Outro')], max_length=20)),
                ('especie_cultivada', models.CharField(choices=[('Tilápia do Nilo (Oreochromis niloticus)', 'Tilápia do Nilo'), ('Tilápia Azul (Oreochromis aureus)', 'Tilápia Azul'), ('Tilápia de Moçambique (Oreochromis mossambicus)', 'Tilápia de Moçambique'), ('Tilápia de Zanzibar (Oreochromis hornorum)', 'Tilápia de Zanzibar'), ('Outro', 'Outro')], max_length=80)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('fonte_agua', models.CharField(blank=True, choices=[('Nascente', 'Nascente'), ('Poço artesiano', 'Poço artesiano'), ('Rio', 'Rio'), ('Abastecimento público', 'Abastecimento público'), ('Outro', 'Outro')], max_length=30)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Manutenção', 'Manutenção'), ('Inativo', 'Inativo')], max_length=20)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('oxigenio', models.FloatField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
