# Generated by Django 5.2.3 on 2025-06-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('preferencia_notificacao', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Email e SMS', 'Email e SMS')], max_length=20)),
                ('senha', models.CharField(max_length=128)),
                ('aceitou_termos', models.BooleanField(default=False)),
            ],
        ),
    ]
