# Generated by Django 5.2.3 on 2025-06-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('volume', models.FloatField()),
                ('capacidade_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('Escavado', 'Escavado'), ('Tanque-rede', 'Tanque-rede'), ('Alvenaria', 'Alvenaria'), ('Fibra de vidro', 'Fibra de vidro'), ('Outro', 'Outro')], max_length=20)),
                ('especie_cultivada', models.CharField(choices=[('Tilápia do Nilo (Oreochromis niloticus)', 'Tilápia do Nilo'), ('Tilápia Azul (Oreochromis aureus)', 'Tilápia Azul'), ('Tilápia de Moçambique (Oreochromis mossambicus)', 'Tilápia de Moçambique'), ('Tilápia de Zanzibar (Oreochromis hornorum)', 'Tilápia de Zanzibar'), ('Outro', 'Outro')], max_length=80)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255)),
                ('fonte_agua', models.CharField(blank=True, choices=[('Nascente', 'Nascente'), ('Poço artesiano', 'Poço artesiano'), ('Rio', 'Rio'), ('Abastecimento público', 'Abastecimento público'), ('Outro', 'Outro')], max_length=30)),
                ('situacao', models.CharField(choices=[('Ativo', 'Ativo'), ('Manutenção', 'Manutenção'), ('Inativo', 'Inativo')], max_length=20)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('oxigenio', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
