# Generated by Django 5.2.3 on 2025-06-28 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tanque'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanque',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tanques', to='core.usuario'),
            preserve_default=False,
        ),
    ]
