# Generated by Django 5.2.3 on 2025-07-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tanque_amonia_tanque_dureza_carbonatos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(choices=[('temperatura', 'Temperatura'), ('ph', 'pH'), ('amonia', 'Amônia'), ('oxigenio', 'Oxigênio'), ('tds', 'TDS'), ('nitrito', 'Nitrito'), ('nitrato', 'Nitrato'), ('dureza_geral', 'Dureza Geral'), ('dureza_carbonatos', 'Dureza Carbonatos'), ('salinidade', 'Salinidade')], max_length=30)),
                ('valor', models.FloatField()),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tanque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='core.tanque')),
            ],
        ),
    ]
