# Generated by Django 5.2.3 on 2025-07-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicosensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alertas_agua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='autenticacao_dois_fatores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='backup_automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='endereco_fazenda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='formato_data',
            field=models.CharField(choices=[('DD/MM/AAAA', 'DD/MM/AAAA'), ('MM/DD/AAAA', 'MM/DD/AAAA'), ('AAAA/MM/DD', 'AAAA/MM/DD')], default='DD/MM/AAAA', max_length=12),
        ),
        migrations.AddField(
            model_name='usuario',
            name='frequencia_backup',
            field=models.CharField(choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Mensal', 'Mensal')], default='Semanal', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idioma',
            field=models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('en-US', 'English (US)'), ('es', 'Español')], default='pt-BR', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lembretes_alimentacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='moeda',
            field=models.CharField(choices=[('R$', 'Real (R$)'), ('$', 'Dólar ($)'), ('€', 'Euro (€)')], default='R$', max_length=3),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome_fazenda',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacoes_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notificacoes_push',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tempo_auto_logout',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='unidade_temperatura',
            field=models.CharField(choices=[('C', 'Celsius (°C)'), ('F', 'Fahrenheit (°F)')], default='C', max_length=1),
        ),
    ]
