# Generated by Django 5.2.3 on 2025-08-09 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_unidade_temperatura_usuario_temperatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('categoria', models.CharField(max_length=50)),
                ('subcategoria', models.CharField(blank=True, max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('quantidade', models.FloatField(blank=True, null=True)),
                ('preco_unitario', models.FloatField(blank=True, null=True)),
                ('valor', models.FloatField()),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('tanque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='core.tanque')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
