# Generated by Django 5.2.3 on 2025-06-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_usuario_groups_remove_usuario_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanque',
            name='volume',
        ),
        migrations.AddField(
            model_name='tanque',
            name='altura',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanque',
            name='comprimento',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tanque',
            name='largura',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
