# Generated by Django 5.2.3 on 2025-08-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosPersonalizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_minimo', models.FloatField(blank=True, null=True)),
                ('ph_maximo', models.FloatField(blank=True, null=True)),
                ('amonia_minima', models.FloatField(blank=True, null=True)),
                ('amonia_maxima', models.FloatField(blank=True, null=True)),
                ('temperatura_minima', models.FloatField(blank=True, null=True)),
                ('temperatura_maxima', models.FloatField(blank=True, null=True)),
                ('oxigenio_dissolvido_minimo', models.FloatField(blank=True, null=True)),
                ('oxigenio_dissolvido_maximo', models.FloatField(blank=True, null=True)),
                ('tds_minimo', models.FloatField(blank=True, null=True)),
                ('tds_maximo', models.FloatField(blank=True, null=True)),
                ('nitrito_minimo', models.FloatField(blank=True, null=True)),
                ('nitrito_maximo', models.FloatField(blank=True, null=True)),
                ('nitrato_minimo', models.FloatField(blank=True, null=True)),
                ('nitrato_maximo', models.FloatField(blank=True, null=True)),
                ('dureza_geral_minima', models.FloatField(blank=True, null=True)),
                ('dureza_geral_maxima', models.FloatField(blank=True, null=True)),
                ('dureza_carbonatos_minima', models.FloatField(blank=True, null=True)),
                ('dureza_carbonatos_maxima', models.FloatField(blank=True, null=True)),
                ('salinidade_minima', models.FloatField(blank=True, null=True)),
                ('salinidade_maxima', models.FloatField(blank=True, null=True)),
                ('tanque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametros_personalizados', to='core.tanque')),
            ],
        ),
    ]
