# Generated by Django 5.2.3 on 2025-11-07 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sensordata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='analises/')),
                ('resultado', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('saudavel', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises_ia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
