# Generated by Django 5.2.3 on 2025-11-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_analiseia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnaliseIA',
        ),
    ]
