# Generated by Django 5.2.3 on 2025-11-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnaliseIA',
        ),
    ]
